apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment

spec:
  replicas: 3

  selector:
    matchLabels:
      app: platform-app

  template:
    metadata:
      labels:
        app: platform-app

    spec:
      containers:
      - name: backend-container
        image: devops-backend:v1
        imagePullPolicy: Never

        ports:
        - containerPort: 5000

        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: DB_HOST

        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: DB_USER

        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: DB_NAME

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: DB_PASSWORD