services:
  backend:
    build: ../app/server
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    environment:
      DB_HOST: postgres
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: appdb

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"