name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

    - name: Deploy manifests
      run: |
        kubectl apply -f k8s/

    - name: Update image in Kubernetes
      run: |
        kubectl set image deployment/backend-deployment \
        backend-container=aresden113/devops-backend:${{ github.run_number }}