name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Verify cluster
      run: kubectl get nodes

    - name: Apply manifests
      run: kubectl apply -f k8s/

    - name: Update image dynamically
      run: |
        kubectl set image deployment/backend-deployment \
        backend-container=aresden113/devops-backend:${{ github.run_number }}

    - name: Verify rollout
      run: kubectl rollout status deployment/backend-deployment