name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Verify cluster
      run: kubectl get nodes

    - name: Apply manifests
      run: kubectl apply -f k8s/

    - name: Restart deployment (force latest)
      run: kubectl rollout restart deployment backend-deployment

    - name: Wait rollout
      run: kubectl rollout status deployment/backend-deployment